<?php

namespace App\Controller\Admin;

use App\Entity\Formation;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use EasyCorp\Bundle\EasyAdminBundle\Provider\AdminContextProvider;

class FormationCrudController extends AbstractCrudController
{
    public function __construct(AdminContextProvider $adminContextProvider) {
        $this->adminContextProvider = $adminContextProvider;
    }
    public static function getEntityFqcn(): string
    {
        return Formation::class;
    }

    public function configureFields(string $pageName): iterable
    {

        return [
            TextField::new('title'),
            TextEditorField::new('description'),
            AssociationField::new('professor')->onlyOnIndex()
        ];
    }

    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        $this->adminContextProvider
            ->getContext()
            ->getUser()
            ->getProfessor()
            ->addFormation($entityInstance);
        parent::persistEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }

}
